
collections:
  archive:
    output: true

exclude: ["originals"]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      conference: RuseConf
      base_uri: "https://kktsvetkov.github.io/ru53c0nf"
